name 'deploy_core'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
source_url 'https://github.com/JonathanSerafini/chef-common_deploy'
issues_url 'https://github.com/JonathanSerafini/chef-common_deploy/issues'
license 'apachev2'
description 'Common chef cookbook providing attribute driven application deployments'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_verison '>= 12.7'
version '0.1.0'
depends 'common_attrs'
